### ISSUE TITLE
Bad creation on index.rest

### ISSUE THREAD

**Issue by emvalbuena** [mmngreco/sphinx-automated#1]
Attempting to use the code led to unexpected behaviour, where the `index.rst` file was created as `index'.rst'`, and writing it in that way in the conf.py

**Comment by asdf8601** [comment]
Yep, This is a windows issue due to the backslashes in the path.

**Comment by asdf8601** [comment]
Actually it was an quoting mark issue. In the windows command line we should use double quotes for raw strings.

The solution was changing `"'.rs'"` by `"\".rst\""` in the code.
